# Generated by Django 4.0.4 on 2022-04-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studentdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=90)),
                ('student_address', models.TextField()),
                ('student_dob', models.DateField()),
                ('student_email', models.EmailField(max_length=254)),
                ('student_phoneno', models.CharField(max_length=50)),
                ('student_gender', models.CharField(max_length=50)),
                ('student_qualification', models.CharField(max_length=50)),
                ('student_course', models.CharField(max_length=50)),
            ],
        ),
    ]
