# Generated by Django 4.0.4 on 2022-04-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0002_studentdetails_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='image',
            field=models.ImageField(blank=True, default='defult2.jpg', null=True, upload_to='image/'),
        ),
    ]
